// <auto-generated />
using System;
using FoodSafetyDashboard.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FoodSafetyDashboard.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FoodSafetyDashboard.Data.Models.Audit", b =>
                {
                    b.Property<long>("AuditId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("audit_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("AuditId"));

                    b.Property<DateTime?>("AuditEnd")
                        .HasColumnType("datetime2")
                        .HasColumnName("audit_end");

                    b.Property<DateTime?>("AuditStart")
                        .HasColumnType("datetime2")
                        .HasColumnName("audit_start");

                    b.Property<string>("Auditor")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("auditor");

                    b.Property<int?>("CriticalViolations")
                        .HasColumnType("int")
                        .HasColumnName("critical_violations");

                    b.Property<string>("Departamento")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("departamento");

                    b.Property<string>("Franchisee")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("franchisee");

                    b.Property<string>("Location")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("location");

                    b.Property<string>("ManagerInCharge")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("manager_in_charge");

                    b.Property<string>("Municipio")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("municipio");

                    b.Property<decimal?>("PercentageScore")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("percentage_score");

                    b.Property<int?>("PointsEarned")
                        .HasColumnType("int")
                        .HasColumnName("points_earned");

                    b.Property<int?>("PointsPossible")
                        .HasColumnType("int")
                        .HasColumnName("points_possible");

                    b.Property<string>("SourceFile")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("source_file");

                    b.Property<int?>("StoreId")
                        .HasColumnType("int")
                        .HasColumnName("store_id");

                    b.Property<int?>("TotalViolations")
                        .HasColumnType("int")
                        .HasColumnName("total_violations");

                    b.HasKey("AuditId");

                    b.ToTable("audits");
                });

            modelBuilder.Entity("FoodSafetyDashboard.Data.Models.AuditFinding", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("AnswerValue")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("answer_value");

                    b.Property<long>("AuditId")
                        .HasColumnType("bigint")
                        .HasColumnName("audit_id");

                    b.Property<string>("CommentText")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("comment_text");

                    b.Property<int?>("EvidencePage")
                        .HasColumnType("int")
                        .HasColumnName("evidence_page");

                    b.Property<string>("FindingType")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("finding_type");

                    b.Property<int?>("PointsEarned")
                        .HasColumnType("int")
                        .HasColumnName("points_earned");

                    b.Property<int?>("PointsPossible")
                        .HasColumnType("int")
                        .HasColumnName("points_possible");

                    b.Property<string>("QuestionText")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("question_text");

                    b.Property<string>("SectionName")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("section_name");

                    b.HasKey("Id");

                    b.HasIndex("AuditId");

                    b.ToTable("audit_findings");
                });

            modelBuilder.Entity("FoodSafetyDashboard.Data.Models.AuditSection", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("AuditId")
                        .HasColumnType("bigint")
                        .HasColumnName("audit_id");

                    b.Property<int?>("PointsEarned")
                        .HasColumnType("int")
                        .HasColumnName("points_earned");

                    b.Property<int?>("PointsPossible")
                        .HasColumnType("int")
                        .HasColumnName("points_possible");

                    b.Property<string>("SectionName")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("section_name");

                    b.Property<decimal?>("SectionScore")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("section_score");

                    b.Property<int?>("TotalViolations")
                        .HasColumnType("int")
                        .HasColumnName("total_violations");

                    b.HasKey("Id");

                    b.HasIndex("AuditId");

                    b.ToTable("audit_sections");
                });

            modelBuilder.Entity("FoodSafetyDashboard.Data.Models.AuditFinding", b =>
                {
                    b.HasOne("FoodSafetyDashboard.Data.Models.Audit", "Audit")
                        .WithMany("Findings")
                        .HasForeignKey("AuditId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Audit");
                });

            modelBuilder.Entity("FoodSafetyDashboard.Data.Models.AuditSection", b =>
                {
                    b.HasOne("FoodSafetyDashboard.Data.Models.Audit", "Audit")
                        .WithMany("Sections")
                        .HasForeignKey("AuditId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Audit");
                });

            modelBuilder.Entity("FoodSafetyDashboard.Data.Models.Audit", b =>
                {
                    b.Navigation("Findings");

                    b.Navigation("Sections");
                });
#pragma warning restore 612, 618
        }
    }
}
